### ISSUE TITLE
User story homepage overview

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#1]
## Value Proposition

As a user,
I want to see my car (if there is a car),
and i want to be able to go to the edit, so that i can create/edit the car

## Description

... (Wireframe, scribble, design or text)
​

## Acceptance Criteria

- [ ] Car/Profile is shown on the homepage
- [ ] The Picture should work as a link
- [ ] If there is no car, a placeholder should be displayed

      ​

## Tasks

- [ ]Create an img element as a link, that links to the profile-page
- [ ]If there is no car registrated, create an placeholder
      ​

## Complexity

M

**Comment by janneserichsen** [comment]
Hey Andreas looks good to me

**Comment by NikRoe** [comment]
Hey Andreas,
this looks like a very promising start!

I would, however, try to shorten the user story in some places.

You intend to display several links that lead to pages that don't exist yet. You should not have a link that leads nowhere - even if you intend to implement an according feature at a later point.
You should only display links/buttons etc. that already have functionality, to prevent bad user experience.

The image is also supposed to link to another page. Does an according page already exist or would the link lead nowhere for the moment?

I would leave out all links that lead to pages that will come at a later point.
You can implement the links to the respective pages when you implement those pages.

For this user story I would most likely:
- display the home page 
- display the image (only make it a link, if there is already a profile-page)
- display a placeholder, if there is no image

Hope this already helps!

**Comment by NikRoe** [comment]
Hi Andreas,
your value proposition should be more concise. Like this:

As a user,
I want have an overview page
So that i can navigate to sub pages.

In your acceptance criteria you should mention what happens in which cases.
- When I click on the link I get redirected to page so and so
- etc....

You most likely need:
- an image component
- a link component
-> You should mention this as well

Will there be a component for the title? If so, mention it in your user story.

**Comment by d-opri** [comment]
you might want to create a component to reuse for the links. otherwise looks goo to me :)

**Comment by JohannesMisch** [comment]
Hey, your user story is really great, for your next one try not to implement empty "code boxes"
