### ISSUE TITLE
create AddEvent 

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#10]
## Value Proposition

**As a** user
**I want to** be able to add new events
**so that** i can add new events if i want
​

## Description

![image](https://user-images.githubusercontent.com/117731514/213728075-b7dec4f9-3197-41b8-a415-0fa79573d4e5.png)​
![image](https://user-images.githubusercontent.com/117731514/213728909-01aa06e1-8f38-4b64-a159-c1f0264b01f3.png)

## Acceptance Criteria

- [ ] There should be a button, on the wishlist, latest and upcoming page
- [ ] If the button is clicked, you should be able to add a new event
- [ ] If the form is submitted the event should be displayed on the page
      ​

## Tasks

- [ ] Create a AddButton component 
- [ ] Include the components on wishlist/latest/upcoming index.js
- [ ] Create a button in that component
- [ ] Create a AddForm component that is displayed when the button is Clicked
- [ ] The form should require "title","descritption","cost","date"
- [ ] onSubmit the form should create a new event and save it in an array
- [ ] The page should rerender with the new Element
      ​

## Complexity

L

**Comment by AstridOttmann** [comment]
What about ...
...so that I stay up to date
in the Value Proposition?

I don't get clearly, if you show the whole list with the new element or only the new element after submitting the event. 

Your heading wishlist/upcomig/latest in the wireframe was a bit confusing at the first look (you can mix up with a navigation, when you don't know your previous story), but in the text it becomes clear that you reuse the functionality for the three pages

**Comment by Long-HaHoang** [comment]
You can also add the form to your acceptance criteria.

- [ ] If the `+ Add event` button is pressed the input form is displayed.

As mention before. Your value proposition doesn't reflect about what you are doing in task.
If I want to be up-to-date I usually expect just a list with events. 

Furthermore I would remove upcoming and latest from the header.
You mentioned, that it's similar but it's not part of this story and I assume those are future pages you want to create.
If you do all three in this single page, then it's ok, but if not I wouldn't mention them yet.

**Comment by AGeck113** [comment]
Hi together,
thank you for the input! 
I follow your suggestion and work just on the "upcoming" page. The other nes get an own US later on and I modified the US so that is clear.

**Comment by AstridOttmann** [comment]
Looks good to me now!

**Comment by JohannesMisch** [comment]
Hey @AGeck113 your user story looks great! One small thing, I don't quite get if you want to display the list with all the existing events all the time, or are they only displayed after you create a new event? Could you clarify that, otherwise like i said your story looks great!

**Comment by AGeck113** [comment]
Thank you! I updated that points to: 
- [ ]  All existing events are displayed the whole time
- [ ] Create a AddForm component that is displayed between the headline and the existing events  when the button is Clicked

**Comment by JohannesMisch** [comment]
LGTM 🥳
