### ISSUE TITLE
Add new Car

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#13]
## Value Proposition

**As a** user
**I want to** register my car
**so that** I can see the data
​

## Description

![image](https://user-images.githubusercontent.com/117731514/214056040-e713fa08-b73e-4725-8a9b-5ce1170647a9.png)​

## Acceptance Criteria

- [ ] The user should be able to register his card with the vin
- [ ] The user should be able to register his car manually
- [ ] onSubmit the user should be redirected to the details page, if the vin is found
- [ ] If the vin is not found, an error message is displayed and he has the option to use the form
      ​

## Tasks

- [ ] Create the profile/index.js 
- [ ] On profile/index.js create an input for the VIN
- [ ] Write a function, that redirects you to the details if the vin is found
- [ ] If the vin is not found, stay on the page and show a message
- [ ] If the user submits the form, a car is generated with his input and he get's to the details page of that car
      ​

## Complexity

M)

**Comment by RobinWitt** [comment]
Looks good to me! Nice idea to have the optional manual input.

**Comment by RobinWitt** [comment]
Changes look good to me, good luck with this one as it seems to be complex :D
