### ISSUE TITLE
Fake Login / Database 

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#15]
## Value Proposition

**As a** Developer
**I want to** fake a login and connect my cars to a database
**so that** that i can save changes and be prepared for a login
​

## Description

... (Wireframe, scribble, design or text)
​

## Acceptance Criteria

- [ ] A Mongo DB Atlas DB should be created
- [ ] In the DB there should a collection for User cars
- [ ] There should also be one collection named carDatabase (which will be replaced by the api later on) 
- [ ] The static JSON should be removed and the DB implemented
      ​

## Tasks

- [ ] Create the Mongo DB
- [ ] Create a const named users like [{id: userid,  car: "vin", name:"testname"}.....]
- [ ] Create a collection named cars, which should save the users car 
- [ ] Create a collection named CarDatabase, which holds the data of all cars (that will be replaced with an API later on)
- [ ] Remove the db/db.JSON from the project
- [ ] Implement the DB, so that the car of the active user is rendered
      ​

## Complexity

L

**Comment by janneserichsen** [comment]
Hey Andreas this looks good to me 👌🏽
