### ISSUE TITLE
feature / Basic styling

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#17]
## Value Proposition

**As a** Developer
**I want to** have basic styling in my app
**so that**it looks a little bit better and is easier to navigate through
​

## Description

![image](https://user-images.githubusercontent.com/117731514/215111096-8a6a4efd-acfb-40dc-bd5a-fb006b217c27.png)​
![image](https://user-images.githubusercontent.com/117731514/215111139-286b3fea-1866-4c32-9b8e-5d6ef6a2f1ab.png)

## Acceptance Criteria

- [ ] The App should have a basic styling without 
- [ ] It should be easier to navigate through the app
      ​

## Tasks

- [ ] Create Styled components
- [ ] Use them at the different pages​

## Complexity

M

**Comment by JohannesMisch** [comment]
Hey, I don't know what you mean by 
>  - [ ] It should be easier to navigate through the app

next time maybe be a little bit more specific.
But for this one ... have a nice weekend, approved :)

**Comment by Long-HaHoang** [comment]
Looks ok to me. Go for it.
