### ISSUE TITLE
feature/rework/events

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#18]
## Value Proposition

**As a** user
**I want to** see the events of the type I want
**so that** I can get an overview over my events
​

## Description
Look for the upcoming and latest events:
![image](https://user-images.githubusercontent.com/117731514/215114469-e6b60833-85b0-47b9-a033-0941923c554c.png)​

Look for the wishlist:
![image](https://user-images.githubusercontent.com/117731514/215114559-8b920bc1-8796-4388-8afb-ad4f131e07cc.png)

## Acceptance Criteria

- [ ] /events/upcoming should render a list of upcoming events
- [ ] /events/latest should render a list of the latest events
- [ ] /event/wishlist should render a list of all events with the type "wishlist"
      ​

## Tasks

- [ ] rename the upcomingEvents/index.js to events/[type].js
- [ ] delete the faked const events
- [ ] Add an array "events" to the userCars in the database, where the events are saved
- [ ] the page should fetch all events of the activeCar with the respective types
- [ ] each event is shown as a event component(component exists already)
      ​

## Complexity

M

**Comment by Long-HaHoang** [comment]
You have a typo in your third criteria.
You have `event` singular instead of `events` plural

But in my honest opinion I would rewrite those.

- [ ] In the `upcoming` page a list of upcoming events is displayed
- [ ] In the `latest` page a list of the latest events is displayed
- [ ] In the `wishlist` page a list of events with the type `wishlist` is displayed

**Comment by Long-HaHoang** [comment]
In the acceptance criteria you should use more simple wordings.
The technical part should be in `Tasks`

**Comment by AGeck113** [comment]
Hi Long, Thank you, I changed it to the way you suggested.

**Comment by IrisHerholz** [comment]
Looks like its working out ! 👍
