### ISSUE TITLE
Profile Page and 

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#2]
## Value Proposition

As a user, 
i want to be able to add my car with the VIN, 
so that most of my car data is auto-filled. I also want to be able to edit the auto-filled data, to correct them if I made any changes on the car, so that the data is correct. 
If my car is registrated, 
i want to see the most important data of my car displayed on that page, with the option to edit the car.
So that i can keep my profile up to date.
​

## Description

![image](https://user-images.githubusercontent.com/117731514/213428280-7a042509-abe9-4914-b3d2-72f79570db97.png)
![image](https://user-images.githubusercontent.com/117731514/213427797-30fc2945-e0ba-41a8-89da-3599cd4f1575.png)​

## Acceptance Criteria

- [ ] If the user has no registrated car, a form should be displayed, where you can enter your VIN
- [ ] If the VIN is correct, a form should be displayed, that is pre-filled with all available data
- [ ] The form can be edited and submitted
- [ ] If there is a registrated car, the data should be displayed
- [ ] The page should contain a button, which shows a form to edit your car

      ​

## Tasks

- [ ] Create the profile-page index.js
- [ ] Create a form, to check your VIN, which returns the car data. 
- [ ] Make the form is just visible, if there is no car created.
- [ ] Create a form, filled with the car data, that you can edit and submit.
- [ ] Create a section that displays the car data, if there is a car registrated.

      ​

## Complexity

L

**Comment by doemser** [comment]
I would suggest to cut the user-story smaller and only connect the API in a second step. In the first step you could create your vehicle without API. Try to write your user-stories always according to the known scheme, if you would write your user-story according to the scheme, you will quickly notice that it might be too long:

As a user, 
I want the ability to input my car's VIN and have most of the car's data automatically filled in, with the option to edit any incorrect or updated information, 
so that I can ensure the data is accurate.

**Comment by AGeck113** [comment]
That was the plan. I don´t want to include the API right now. I would just create a fake-const with 1 car in it.

**Comment by doemser** [comment]
Oh, I got that wrong, even though I knew it. Try to express yourself more concretely, e.g. in this direction:

1. Create an input field for the user to enter their car's VIN
2. Implement a function to filter the VIN out of a static json to retrieve the car's data
3. Display the retrieved car data on the page
4. Allow the user to edit any of the displayed car data
5. Implement a save button to save any changes made by the user
6. Add validation to ensure that the VIN input is a valid VIN format
7. Show an error message if the VIN is not found or invalid

**Comment by doemser** [comment]
Acceptance Criteria:

1. The user can input their car's VIN and view the automatically filled data
2. The user can edit any of the automatically filled data
2. The user can save any changes they make to the car's data
3. The input field for the VIN is in the correct format
4. An error message is displayed if the VIN is not found or invalid
5. The saved data is reflected on the page

**Comment by NikRoe** [comment]
Hi Andreas,

for the moment, the user story is too big. You should split it up intro 2-3 smaller user stories.

You mention a form that will be shown for users where the VIN search gave no results. It can be part of this user story (though one could argue that it could even be a separate story), but from the wireframes in the description, it is not clear, how the form will look. Please add a wireframe for that form, if you intend to keep it in the user story.
Applying this change will leave you with either 1 or 2 user stories.

Editing existing cars should be a separate user story.

-> for the current user story to work: 
- remove the edit button from the wireframe 
- remove the mention of the edit button from the tasks
- add a wireframe for entering your car in a form, if the search lead to no results
