### ISSUE TITLE
feature/ Upload Image/Cloudinary

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#22]
## Value Proposition

**As a** User
**I want to** upload a picture of my car
**so that** I can see it on the landing page and profile page
​

## Description

![image](https://user-images.githubusercontent.com/117731514/216284842-e5c6e8e4-344d-412d-8bc7-06233d8f62eb.png)​
![image](https://user-images.githubusercontent.com/117731514/216284915-30b24af6-d96c-4089-98cc-0d645c731ad2.png)

## Acceptance Criteria

- [ ] The user should be able to upload a picture of his car
- [ ] The new Picture should be shown on the profile
- [ ] The new Picture should be displayed on the landing page
      ​

## Tasks

- [ ] The cars in the database already have the key "imageUrl" with a string
- [ ] Rewrite the input field for the Url from "string" to an input type "file"
- [ ] Rewrite the submit function, so that it sends the file to cloudinary
- [ ] the recieved URL from cloudinary should be saved as the imageUrl
      ​

## Complexity

M

**Comment by JoergWolff** [comment]
LGTM
