### ISSUE TITLE
feature/ appointment-warning

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#23]
## Value Proposition

**As a** User
**I want to** get a notification about near appointments
**so that** I can react and decide what to do
​

## Description

![image](https://user-images.githubusercontent.com/117731514/216297834-019d4de2-89df-44a0-b3a4-4aad2df8a11c.png)​

## Acceptance Criteria

- [ ] If there are no near/missed events, the page should be displayed without the warning
- [ ] If there are near events, the should be displayed
- [ ] If there are missed events, they should be displayed and marked with red
      ​

## Tasks

- [ ] On the landing page, check if the car has near/missed events
- [ ] create a component, that recieves a list of near/missed Events and renders a card for each of them
- [ ] Implement the component in the landing page
- [ ] Render the component only if there are missed/near events
      ​

## Complexity

M

**Comment by AstridOttmann** [comment]
Looks good!
In your acceptance criteria one word (warning or so) is missing ;-)
'near' means "in der Nähe", maybe you mean next?

**Comment by AGeck113** [comment]
Thank you, it was a missing "y" 😄  It should mean something like "appointments in the next 30 days". But I think about that.
