### ISSUE TITLE
feature/EventDetailPage

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#24]
## Value Proposition

**As a** user
**I want to** be able to save documents to my appointments
**so that** I know where i can find it if i need it
​

## Description

![image](https://user-images.githubusercontent.com/117731514/216334187-0bb19559-019b-413d-90f4-8f3587fa59c4.png)

- [ ] The user should be able to click on the appointments title and get directed to a detail page
- [ ] On the detail page, the data of the appointment is shown
- [ ] There should be a section with 2 tabs (notes and documents)
- [ ] On the notes tab, the user should see his notes, edit them and save them
- [ ] On the documents tab, the user is able to see a list of his documents to the appointment
- [ ] The user is able to upload documents
      ​

## Tasks

- [ ] Create the EventDetail page
- [ ] Display the data of the Appointment with the Event component
- [ ] Add a section
- [ ] Add the options "notes" and "documents"
- [ ] Create component Documents, that works with cloudinary
- [ ] Create component Notes
      ​

## Complexity

L

**Comment by RobinWitt** [comment]
Looks good to me! To have the documents for the appointment is a great idea.
