### ISSUE TITLE
feature/EventsMap

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#25]
## Value Proposition

**As a** user
**I want to** find car meetings in my
**so that** I could go there
​

## Description

![image](https://user-images.githubusercontent.com/117731514/216339218-70f13cd3-8c4a-485b-b116-80219d40c519.png)​

## Acceptance Criteria

- [ ] There should be a Navigation on the Homepage to "Events"
- [ ] On the page is a map, where different locations are marked
- [ ] If you click them, the Name and date of the event is shown
- [ ] The events provide a google Maps link
      ​

## Tasks

- [ ] Create the "event/index.js"
- [ ] create a heading
- [ ] Create a navigation back to the landing Page
- [ ] implement a leaflet Map
- [ ] Create a mongoDB collection for events with 3 or 4 events
- [ ] Display the markers on the map
      ​

## Complexity

XL

**Comment by RobinWitt** [comment]
Looks good to me, just some missing words in your Value Proposition:
"As a user
I want to find car meetings in my **region**
so that I could go there"
