### ISSUE TITLE
feature/nextAuth

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#29]
## Value Proposition

**As a** User
**I want to** be able to create an account and log in
**so that** no one else could see the data of my car
​

## Description

![image](https://user-images.githubusercontent.com/117731514/217305461-2a386610-6559-4023-8dad-7e7dacfa7c06.png)​

## Acceptance Criteria

- [ ] The user should be able to create a profile
- [ ] The user should be able to log into his profile
- [ ] Only the data of the current user should be displayed
- [ ] No data is displayed if the user isn't logged in
      ​

## Tasks

- [ ] Take part in the nextAuth workshop
- [ ] Create Login Page
- [ ] Implement the login from nextAuth
- [ ] Redirect the user to the login page, from any other page, if he's not logged in
      ​

## Complexity

L

**Comment by marcterre** [comment]
Hey Andreas, you didnt mention the submit buttons the user need to send data.
Does the user start on this page, so the user has to login first and then will be redirected to his data? Or does he click on a button to go to the login page?
If the User starts on this page you dont need the last point in your acceptance criteria. I guess the user is not able to go on any page without login?

**Comment by AGeck113** [comment]
Thank you Marc, i've done some changes.

**Comment by minatimar** [comment]
nice
