### ISSUE TITLE
Upcoming events

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#3]
## Value Proposition

**As a user**
**I want to** be able to create upcoming events for my car
**so that** i can see what is planned and how much it costs.
​

## Description

![image](https://user-images.githubusercontent.com/117731514/213435249-2e37386f-e451-4e9c-b1fc-abd55593a3b9.png)​

## Acceptance Criteria

- [ ] The user should be able to create events
- [ ] The created events are displayed
- [ ] The user should be able to edit the events
- [ ] The total costs are displayed at the bottom
      ​

## Tasks

- [ ] create the upcoming events page
- [ ] Create an add button, which shows a form when clicked
- [ ] Create a list of events, that is displayed on the page
- [ ] Create a section at the bottom, that shows all planned costs
      ​

## Complexity

M

**Comment by NikRoe** [comment]
Hi Andreas,
promising start!

Some suggestions and notes:
Your value proposition can be shortened:

As a user
I want to be able to create upcoming events for my car
so that i can see what is planned

In your acceptance criteria you should specify, what will happen when you click on the add button (most likely a form will appear) and what happens after submitting the form.

Editing existing entries should be a separate user story.

How will the sub page be linked to the home page? Will there be a back button? If so, where will it be displayed?

Apart from that you user story looks really nice 🙌

**Comment by RobinWitt** [comment]
Hi Andreas, the scope of this story looks good.
But it is not clear to me from which resource you get the events. Maybe you can clarify that in your tasks?

**Comment by magjo21** [comment]
Hi Andreas, 
Looks very good!
