### ISSUE TITLE
feature/FinalCheck

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#32]
## Value Proposition

**As a** developer  
**I want to** check my code for small improvements   
**so that** I can optimize my code 
​

## Acceptance Criteria

- [ ] The App runs without errors
- [ ] Everything is styled correctly
- [ ] No unused code is left in the project
      ​

## Tasks

- [ ] Check the code for unused lines
- [ ] Run Lighthouse and fix all issues
- [ ] Check the final version intensively in the Preview
- [ ] to be sure no errors occur
      ​

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by Long-HaHoang** [comment]
Good, refactor story. Happy coding.
