### ISSUE TITLE
Profile Page - edit Car

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#4]
## Value Proposition

**As a user** with a saved car,  I want to  see the most important data of my car displayed on that page, with the option to edit the car.
So that i can keep my profile up to date.

## Description

![image](https://user-images.githubusercontent.com/117731514/213427797-30fc2945-e0ba-41a8-89da-3599cd4f1575.png)​​

## Acceptance Criteria

- [ ] The information about the car should be displayed
- [ ] The user can edit his car
      ​

## Tasks

- [ ] Create a section where the data is displayed
- [ ] Create a button, that shows a form onClick
- [ ] The form should be pre-filled with the car data
​

## Complexity

M

**Comment by NikRoe** [comment]
Hi Andreas,
you should write your value proposition more concise. Like this:

As a user, 
I want to be able to edit my car,
So that i can keep my profile up to date

You mention that a form will be used. Do you already have a form component from a previous user story or will this be part of the current user story? If it is part of the current user story, please mention creating the form component and what else entails implement this new component
