### ISSUE TITLE
Latest events

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#5]
## Value Proposition

**As a user**
**I want to** be able to see the latest events for my car
**so that** i can see what was done and how high the cost was
​

## Description
![image](https://user-images.githubusercontent.com/117731514/215103237-407b9c0d-f12a-47b3-a53c-6369fda89962.png)

![image](https://user-images.githubusercontent.com/117731514/215077736-06498c8f-68d6-4a5d-8c60-d4cfb71e4a78.png)

## Acceptance Criteria
- [ ] All latest events should be displayed
- [ ] They should be in order of the date
- [ ] Each event should show the title, the date, the est. cost and the priority
- [ ] The total costs are displayed at the bottom
      ​

## Tasks

- [ ] create the latest events page
- [ ] In my database, the cars already have a key "events:[{},{}]". Now add to the event Objects a key named "type"
- [ ] Go to the upcoming events and cut all the logic from there
- [ ] Implement the logic in a Component "eventList"
- [ ] The component should get a prop named "type", that decides which events from the array should be shown
- [ ] each event is displayed by an event component
- [ ] Go back to the upcoming page and include the component, give it the prop type=""upcoming"
- [ ] On the latest events, include the component with the prop "latest"

## Complexity

S

**Comment by TariqAlQadi** [comment]
Looks good to me :)

**Comment by RobinWitt** [comment]
Looks to me like the wireframe doesn't seem to fit the text in this updated User Story. The text content makes sense to me though.

**Comment by AGeck113** [comment]
Thanks! In the view of the upcoming events, nothing should change, i just want to extract the logic from there into a component and use that for both pages. Now I included the Wireframe for this page now aswell.
