### ISSUE TITLE
CarDetail Page

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#6]
## Value Proposition

**As a**user
**I want to**see the available information about my car 
**so that**I can check and edit it.
​

## Description

![image](https://user-images.githubusercontent.com/117731514/213648516-90d3305c-87ea-4180-a5fb-c216194bc73c.png)​

## Acceptance Criteria

- [ ] The data of the car is displayed 
- [ ] There should be a button, where you can edit the data
- [ ] An Edit-Form is displayed, when the  button is clicked
- [ ] The Form is removed onSubmit and the new data is displayed
      ​

## Tasks

- [ ] Create a page profile/[vin].js
- [ ] Implement a function to filter the VIN out of a static json to retrieve the car's data, that includes make, model, year etc.
- [ ] The page should render the car with the correct vin
- [ ] Create a state, isEditing
- [ ] Create a form, with the default Value of the car
- [ ] Create a button, that shows a Form 
- [ ] The Form should have the default Value of the Cars data

      ​

## Complexity

M

**Comment by doemser** [comment]
Is this user-story about creating a details card, or about editing details? This is not clear to me, but I would say that these could be two different user stories.

As a user, I want to be able to create a new detailed page for a car in my collection, so that I can keep track of relevant information about my vehicle.

As a user, I want to be able to edit the details of a specific car in my collection, so that I can keep my car collection up-to-date and accurate.

**Comment by NikRoe** [comment]
Very nice, Andreas! 🙌
