### ISSUE TITLE
Car Details - Edit

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#7]
## Value Proposition

**As a** user
**I want to** .edit the data of my car
**so that** I can keep the data up to date
​

## Description

![image](https://user-images.githubusercontent.com/117731514/213675471-8157ca10-39bb-4ae3-a5a1-a24745ac9d0c.png)​

## Acceptance Criteria

- [ ] There should be a button to edit my cars data
- [ ] The button should show a form
- [ ] The form should have the default Value of my car
- [ ] Show the details page again, if the form is submitted
- [ ] The Detail page should show the edited data
      ​

## Tasks

- [ ] On [vin].js Create a state isEditing
- [ ] Create a button, that toggles isEditing
- [ ] Create a form, with the default value of my cars data
- [ ] Make the form only appear, if the user is editing
- [ ] Create a onSubmit function, that saves the new data (for now, as a state), and rerenders the page, with the correct informations
      ​

## Complexity

M

**Comment by NikRoe** [comment]
Hey Andreas,

the user story looks very nice!

Only one small note regarding your acceptance criteria:
- clicking the button shows a form

And please provide a wireframe where that form is shown.

Apart from that, really good and keep it up.

**Comment by AGeck113** [comment]
Thank you Niklas,  I updated the US.

**Comment by marcterre** [comment]
Hey Andreas,
maybe place the button inside of your car details because you only want to edit this part and not the picture (Or can you edit the picture too?)?
Have fun

**Comment by AGeck113** [comment]
Hi Marc, 
for now, the picture is a fake url, in the future it should be a picture of the users car. 
You can edit the url because my data provides no picture, so there is just a placeholder at the beginning.
