### ISSUE TITLE
Wishlist page

### ISSUE THREAD

**Issue by AGeck113** [AGeck113/capstone-project#9]
## Value Proposition

**As a user**
**I want to** be able to look at items on my Wishlist
**so that** i can see what my plans are and how important they are
​

## Description

![image](https://user-images.githubusercontent.com/117731514/213722533-a3333fc3-dbdf-42e9-a7ed-80d994ec4bde.png)

## Acceptance Criteria
- [ ] All events should be displayed
- [ ] They should be in order of the priority
- [ ] Each event should show the title, the date, the est. cost and the priority
- [ ] The total costs are displayed at the bottom
      ​

## Tasks

- [ ] create the wishlist page
- [ ] Create (for now) an array of 3 events 
- [ ] Display list of all events
- [ ] reuse event component
- [ ] each event is displayed by an event component
- [ ] Create a section at the bottom, that shows all planned costs

## Complexity

S

**Comment by TariqAlQadi** [comment]
Seems like a good user story :)
